#!/bin/bash
# 初始化
echo "Starting Time Monitor..."
touch /usr/share/nginx/html/time.txt

# 循环更新时间文件
while true; do
  # 将当前时间写入 time.txt
  # 这样 Nginx 就可以提供这个静态文件供前端 JS 读取
  date +"%Y-%m-%d %H:%M:%S" > /usr/share/nginx/html/time.txt
  
  sleep 1
done
