#!/bin/bash
echo "[Network Check] 正在检查网络连通性..."
if curl -s --head  --request GET http://www.google.com | grep "200 OK" > /dev/null; then
    echo "[Network Check] 网络连接正常！"
    exit 0
else
    echo "[Network Check] 警告：无法连接外网，但 Nginx 将继续尝试启动。"
    exit 0 # 即使失败我们也退出 0，否则 s6 会阻止后续 Nginx 启动
fi